[theme]
primaryColor = "#004C6D"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#212529"
font = "sans serif"

[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false
